version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 7
    cooldown:
      default-days: 3
    groups:
      gh_build:
        patterns:
          - '*'